version: '3'

services:
  server:
    image: registry.gitlab.com/commento/commento
    ports:
      - 8080:8080
    environment:
      COMMENTO_ORIGIN: http://commento.example.com:8080
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://hubiteng:123456@db:5432/commento?sslmode=disable
    depends_on:
      - db
    #networks:
    #  - db_network
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: hubiteng
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 8432:5432
    #networks:
    #  - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

networks:
  db_network:

volumes:
  postgres_data_volume:
